# GitHub Sponsors configuration (optional)
# Uncomment and add your sponsor links

# github: [ben-saito]
# patreon: your-patreon
# ko_fi: your-kofi
# custom: ["https://buymeacoffee.com/your-username"]
